// Turkish country label → flag emoji, for the curated legends dataset (whose
// countries are written in Turkish). Falls back to a white flag if unknown.
const FLAGS: Record<string, string> = {
  Türkiye: '🇹🇷',
  Brezilya: '🇧🇷',
  Arjantin: '🇦🇷',
  İtalya: '🇮🇹',
  Almanya: '🇩🇪',
  Fransa: '🇫🇷',
  İngiltere: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  Hollanda: '🇳🇱',
  İspanya: '🇪🇸',
  Portekiz: '🇵🇹',
  Uruguay: '🇺🇾',
  Şili: '🇨🇱',
  Kolombiya: '🇨🇴',
  Paraguay: '🇵🇾',
  Peru: '🇵🇪',
  Ekvador: '🇪🇨',
  Bolivya: '🇧🇴',
  Venezuela: '🇻🇪',
  Meksika: '🇲🇽',
  ABD: '🇺🇸',
  'Kosta Rika': '🇨🇷',
  Honduras: '🇭🇳',
  Liberya: '🇱🇷',
  Kamerun: '🇨🇲',
  Nijerya: '🇳🇬',
  Gana: '🇬🇭',
  'Fildişi Sahili': '🇨🇮',
  Senegal: '🇸🇳',
  Mali: '🇲🇱',
  Togo: '🇹🇬',
  'Güney Afrika': '🇿🇦',
  Mısır: '🇪🇬',
  Fas: '🇲🇦',
  Cezayir: '🇩🇿',
  Zambiya: '🇿🇲',
  'Rusya / SSCB': '🇷🇺',
  Ukrayna: '🇺🇦',
  Gürcistan: '🇬🇪',
  Bulgaristan: '🇧🇬',
  Romanya: '🇷🇴',
  'Çekya / Çekoslovakya': '🇨🇿',
  Slovakya: '🇸🇰',
  Polonya: '🇵🇱',
  Macaristan: '🇭🇺',
  Hırvatistan: '🇭🇷',
  Sırbistan: '🇷🇸',
  Karadağ: '🇲🇪',
  'Kuzey Makedonya': '🇲🇰',
  'Bosna-Hersek': '🇧🇦',
  Slovenya: '🇸🇮',
  İsveç: '🇸🇪',
  Danimarka: '🇩🇰',
  Norveç: '🇳🇴',
  Finlandiya: '🇫🇮',
  İzlanda: '🇮🇸',
  İskoçya: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  Galler: '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
  'Kuzey İrlanda': '🇬🇧',
  İrlanda: '🇮🇪',
  Belçika: '🇧🇪',
  Avusturya: '🇦🇹',
  İsviçre: '🇨🇭',
  Yunanistan: '🇬🇷',
  Japonya: '🇯🇵',
  'Güney Kore': '🇰🇷',
  İran: '🇮🇷',
  'Suudi Arabistan': '🇸🇦',
  Çin: '🇨🇳',
  Avustralya: '🇦🇺',
}

export function countryFlag(country: string): string {
  return FLAGS[country] ?? '🏳️'
}
