// Maps an API-Football nationality string to a flag. National teams that are
// not ISO countries (the Home Nations) use the emoji tag sequences; everyone
// else derives a regional-indicator flag from their ISO 3166-1 alpha-2 code.
// The map covers every nationality currently present in our data.
const ISO2: Record<string, string> = {
  Albania: 'AL',
  Algeria: 'DZ',
  Andorra: 'AD',
  Angola: 'AO',
  Argentina: 'AR',
  Armenia: 'AM',
  Aruba: 'AW',
  Australia: 'AU',
  Austria: 'AT',
  Azerbaijan: 'AZ',
  Belarus: 'BY',
  Belgium: 'BE',
  Benin: 'BJ',
  Bermuda: 'BM',
  Bolivia: 'BO',
  'Bosnia and Herzegovina': 'BA',
  Brazil: 'BR',
  Bulgaria: 'BG',
  'Burkina Faso': 'BF',
  Burundi: 'BI',
  Cameroon: 'CM',
  Canada: 'CA',
  'Cape Verde': 'CV',
  'Central African Republic': 'CF',
  Chad: 'TD',
  Chile: 'CL',
  'China PR': 'CN',
  Colombia: 'CO',
  Comoros: 'KM',
  Congo: 'CG',
  'Congo DR': 'CD',
  'Costa Rica': 'CR',
  Croatia: 'HR',
  Cuba: 'CU',
  'Curaçao': 'CW',
  Cyprus: 'CY',
  'Czech Republic': 'CZ',
  Czechia: 'CZ',
  "Côte d'Ivoire": 'CI',
  'Ivory Coast': 'CI',
  Denmark: 'DK',
  'Dominican Republic': 'DO',
  Ecuador: 'EC',
  Egypt: 'EG',
  'El Salvador': 'SV',
  'Equatorial Guinea': 'GQ',
  Estonia: 'EE',
  'Faroe Islands': 'FO',
  Finland: 'FI',
  France: 'FR',
  'French Guiana': 'GF',
  Gabon: 'GA',
  Gambia: 'GM',
  Georgia: 'GE',
  Germany: 'DE',
  Ghana: 'GH',
  Gibraltar: 'GI',
  Greece: 'GR',
  Grenada: 'GD',
  Guadeloupe: 'GP',
  Guatemala: 'GT',
  Guinea: 'GN',
  'Guinea-Bissau': 'GW',
  Haiti: 'HT',
  Honduras: 'HN',
  Hungary: 'HU',
  Iceland: 'IS',
  Indonesia: 'ID',
  Iran: 'IR',
  Iraq: 'IQ',
  Israel: 'IL',
  Italy: 'IT',
  Jamaica: 'JM',
  Japan: 'JP',
  Jordan: 'JO',
  Kazakhstan: 'KZ',
  Kenya: 'KE',
  'Korea DPR': 'KP',
  'Korea Republic': 'KR',
  Kosovo: 'XK',
  'Kyrgyz Republic': 'KG',
  Latvia: 'LV',
  Liberia: 'LR',
  Libya: 'LY',
  Liechtenstein: 'LI',
  Lithuania: 'LT',
  Luxembourg: 'LU',
  Madagascar: 'MG',
  Malaysia: 'MY',
  Mali: 'ML',
  Malta: 'MT',
  Martinique: 'MQ',
  Mauritania: 'MR',
  Mexico: 'MX',
  Moldova: 'MD',
  Montenegro: 'ME',
  Montserrat: 'MS',
  Morocco: 'MA',
  Mozambique: 'MZ',
  Netherlands: 'NL',
  'New Zealand': 'NZ',
  Niger: 'NE',
  Nigeria: 'NG',
  'North Macedonia': 'MK',
  Norway: 'NO',
  Pakistan: 'PK',
  Panama: 'PA',
  Paraguay: 'PY',
  Peru: 'PE',
  Philippines: 'PH',
  Poland: 'PL',
  Portugal: 'PT',
  'Puerto Rico': 'PR',
  Qatar: 'QA',
  'Republic of Ireland': 'IE',
  Romania: 'RO',
  Russia: 'RU',
  'Saudi Arabia': 'SA',
  Senegal: 'SN',
  Serbia: 'RS',
  'Sierra Leone': 'SL',
  Slovakia: 'SK',
  Slovenia: 'SI',
  'South Africa': 'ZA',
  Spain: 'ES',
  'St. Kitts and Nevis': 'KN',
  'St. Lucia': 'LC',
  Sudan: 'SD',
  Suriname: 'SR',
  Sweden: 'SE',
  Switzerland: 'CH',
  Syria: 'SY',
  Tanzania: 'TZ',
  Thailand: 'TH',
  Togo: 'TG',
  'Trinidad and Tobago': 'TT',
  Tunisia: 'TN',
  Turkey: 'TR',
  'Türkiye': 'TR',
  USA: 'US',
  Uganda: 'UG',
  Ukraine: 'UA',
  'United Arab Emirates': 'AE',
  Uruguay: 'UY',
  Uzbekistan: 'UZ',
  Venezuela: 'VE',
  Zambia: 'ZM',
  Zimbabwe: 'ZW',
}

// Home Nations flags (emoji tag sequences) — not ISO countries.
const SUBDIVISION: Record<string, string> = {
  England: '🏴\u{E0067}\u{E0062}\u{E0065}\u{E006E}\u{E0067}\u{E007F}',
  Scotland: '🏴\u{E0067}\u{E0062}\u{E0073}\u{E0063}\u{E0074}\u{E007F}',
  Wales: '🏴\u{E0067}\u{E0062}\u{E0077}\u{E006C}\u{E0073}\u{E007F}',
}

function iso2ToEmoji(cc: string): string {
  return cc
    .toUpperCase()
    .replace(/[A-Z]/g, (c) => String.fromCodePoint(127397 + c.charCodeAt(0)))
}

/** Flag emoji for a nationality, or empty string if it can't be resolved. */
export function flagEmoji(nationality: string | null | undefined): string {
  if (!nationality) return ''
  if (SUBDIVISION[nationality]) return SUBDIVISION[nationality]
  const iso = ISO2[nationality]
  return iso ? iso2ToEmoji(iso) : ''
}
